# Generated by Django 5.2.3 on 2025-06-13 12:45

import myapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', myapp.models.CustomUserManager()),
            ],
        ),
    ]
