apiVersion: v1
kind: ConfigMap
metadata:
  name: kub-project-config
  namespace: kub-project
data:
  MYSQL_DATABASE: "kubdb"
  MYSQL_USER: "kubuser"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  KAFKA_BROKER: "kafka:9092"
  REACT_APP_API_URL: "http://backend:8000"
