apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: kub-project
data:
  primary.cnf: |
    # Primary MySQL server configuration
    [mysqld]
    server-id=1
    log_bin=mysql-bin
    binlog_format=ROW
    binlog_do_db=kubdb
  
  replica.cnf: |
    # Replica MySQL server configuration
    [mysqld]
    server-id=2
    log_bin=mysql-bin
    binlog_format=ROW
    binlog_do_db=kubdb
    read_only=1
    super_read_only=1
