apiVersion: v1
kind: Secret
metadata:
  name: kub-project-secrets
  namespace: kub-project
type: Opaque
data:
  # These are base64 encoded values
  # echo -n "rootpassword" | base64
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  # echo -n "kubpassword" | base64
  MYSQL_PASSWORD: a3VicGFzc3dvcmQ=
