version: '3.8'

services:
  kafka:
    build: .
    ports:
      - "9092:9092"
    volumes:
      - ./kafka_data:/bitnami/kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qg
    container_name: kub-kafka

  kafka-producer:
    image: bitnami/kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c "
      sleep 20 &&
      kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic test &&
      echo 'Producing messages to test topic...' &&
      for i in {1..5}; do echo \"Test message $$i\" | kafka-console-producer.sh --bootstrap-server kafka:9092 --topic test; done
      "
    container_name: kub-kafka-producer

  kafka-consumer:
    image: bitnami/kafka:latest
    depends_on:
      - kafka
      - kafka-producer
    command: >
      bash -c "
      sleep 25 &&
      echo 'Consuming messages from test topic...' &&
      kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test --from-beginning --timeout-ms 10000
      "
    container_name: kub-kafka-consumer

volumes:
  kafka_data: 